// GENERATED BY tools/generate_engine_state_fixture.js
// DO NOT EDIT BY HAND.

/// A deterministic Baloot engine state in JSON form (playing phase, 4 players).
const String kTestEngineStateJson = '''
{
  "totals": [
    0,
    0
  ],
  "dealer": 1,
  "handsPlayed": 0,
  "matchOver": false,
  "winnerTeam": null,
  "safeMode": true,
  "autoDeclare": true,
  "players": [
    {
      "name": "Me",
      "isBot": false,
      "uid": "p0",
      "displayName": "Me",
      "team": "A"
    },
    {
      "name": "Faisal",
      "isBot": true,
      "uid": "p1",
      "displayName": "Faisal",
      "team": "B"
    },
    {
      "name": "Omar",
      "isBot": true,
      "uid": "p2",
      "displayName": "Omar",
      "team": "A"
    },
    {
      "name": "Khalid",
      "isBot": true,
      "uid": "p3",
      "displayName": "Khalid",
      "team": "B"
    }
  ],
  "state": {
    "phase": "playing",
    "hands": {
      "0": [
        "8♠",
        "J♥",
        "7♥",
        "K♥",
        "J♠",
        "J♣",
        "8♣",
        "A♣"
      ],
      "1": [
        "K♣",
        "8♦",
        "9♠",
        "7♦",
        "Q♥",
        "10♦",
        "Q♠",
        "A♠"
      ],
      "2": [
        "Q♣",
        "7♣",
        "Q♦",
        "9♣",
        "A♦",
        "10♣",
        "A♥",
        "8♥"
      ],
      "3": [
        "K♦",
        "10♠",
        "10♥",
        "9♦",
        "J♦",
        "K♠",
        "9♥",
        "7♠"
      ]
    },
    "topCard": "8♥",
    "rest": [
      "10♣",
      "A♥",
      "J♣",
      "8♣",
      "A♣",
      "10♦",
      "Q♠",
      "A♠",
      "K♠",
      "9♥",
      "7♠"
    ],
    "firstPlayer": 2,
    "mode": "sun",
    "trump": null,
    "buyer": 2,
    "ashkal": false,
    "bidding": {
      "round": 1,
      "turn": 2,
      "spoken": 0,
      "best": {
        "type": "sun",
        "seat": 2,
        "suit": null
      }
    },
    "currentTrick": [],
    "trickHistory": [],
    "leader": 2,
    "turn": 2,
    "projects": [],
    "countedProjects": [],
    "droppedProjects": [],
    "pendingAnnounce": [],
    "pendingReveal": [],
    "announcedProjects": [],
    "revealedProjects": [],
    "balootTeam": null,
    "balootSeat": null,
    "awaitingDeclare": false,
    "declareSeats": [],
    "declarations": {},
    "doubleLevel": 1,
    "doubleTeam": null,
    "awaitingDouble": false,
    "doubling": null,
    "violation": null,
    "pendingViolations": [],
    "voids": {
      "0": [],
      "1": [],
      "2": [],
      "3": []
    },
    "playedCards": [],
    "result": null
  }
}
''';
