/*
  Generate a deterministic Baloot engine-state fixture for tests.
  Output: test/helpers/engine_state_fixture.dart
*/

const fs = require('fs');
const path = require('path');

const { BalootEngine, BalootSerializer } = require('../functions/lib/engine');

function seededRng(seed = 42) {
  let s = seed;
  return () => {
    s = (s * 9301 + 49297) % 233280;
    return s / 233280;
  };
}

const engine = new BalootEngine(seededRng(12345));
const match = engine.createMatch(
  [
    { uid: 'p0', name: 'Me', displayName: 'Me', team: 'A', isBot: false },
    { uid: 'p1', name: 'Faisal', displayName: 'Faisal', team: 'B', isBot: true },
    { uid: 'p2', name: 'Omar', displayName: 'Omar', team: 'A', isBot: true },
    { uid: 'p3', name: 'Khalid', displayName: 'Khalid', team: 'B', isBot: true },
  ],
  { safeMode: true, autoDeclare: true },
);

engine.startHand(match);

// Move from bidding to playing deterministically by having the first player call Sun.
const firstPlayer = match.state.firstPlayer;
engine.applyBid(match, firstPlayer, { type: 'sun' });

const engineState = new BalootSerializer().serializeMatch(match);

const dartFile = `// GENERATED BY tools/generate_engine_state_fixture.js
// DO NOT EDIT BY HAND.

/// A deterministic Baloot engine state in JSON form (playing phase, 4 players).
const String kTestEngineStateJson = '''
${JSON.stringify(engineState, null, 2)}
''';
`;

const outPath = path.join(__dirname, '..', 'test', 'helpers', 'engine_state_fixture.dart');
fs.writeFileSync(outPath, dartFile, 'utf8');
console.log(`Wrote ${outPath}`);
console.log(`Phase: ${engineState.state.phase}, firstPlayer: ${engineState.state.firstPlayer}, buyer: ${engineState.state.buyer}`);
